# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 246a8b511709cd0eb3291f7eed9f6ea901c5732642e61139c9077db56959b010b726599919ffe41398f7d002686b2cd4fe874f600d09826e35e77f01dd426145

test:
  secret_key_base: 1c79e54c461cd6e1753255ae705fdad8f4e843cd89dac101c0db856e17c12d65c7f4faf356ee0b68941129a0c43f47bb915fef653434d4beb78d97620709e125

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
